-- Database생성
CREATE DATABASE OCO;

-- 계정 생성
CREATE USER 'com_dev'@'%' IDENTIFIED BY 'qwer1234!';

-- 권한 부여
GRANT ALL PRIVILEGES ON OCO.* TO 'com_dev'@'%';
FLUSH PRIVILEGES;

-- 테이블 생성
CREATE TABLE OCO.OCO10100 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USER_NM varchar(30) DEFAULT NULL COMMENT '사용자명',
  CONN_PSSWD varchar(256) DEFAULT NULL COMMENT '접속비밀번호S',
  PSSWD_EXPIR_DT varchar(8) DEFAULT NULL COMMENT '비밀번호만료일자',
  USER_CONT_PHNO varchar(14) DEFAULT NULL COMMENT '사용자연락전화번호',
  USER_EMAILADDR varchar(100) DEFAULT NULL COMMENT '사용자이메일주소',
  DEPTCD varchar(6) DEFAULT NULL COMMENT '부서코드',
  REOFO_CD varchar(3) DEFAULT NULL COMMENT '직책코드',
  VCTN_CD varchar(3) DEFAULT NULL COMMENT '직능코드',
  CUCEN_TEAM_CD varchar(6) DEFAULT NULL COMMENT '고객센터팀코드',
  OFCPS_CD varchar(4) DEFAULT NULL COMMENT '직위코드',
  USER_GROUP_CD varchar(1) DEFAULT NULL COMMENT '사용자그룹코드',
  INNER_USER_CL_CD varchar(1) DEFAULT NULL COMMENT '내부사용자구분코드',
  USER_IDENT_NO varchar(10) DEFAULT NULL COMMENT '사용자식별번호',
  USERID_STS_CD varchar(1) DEFAULT NULL COMMENT '사용자ID상태코드',
  FST_REG_DTMD datetime DEFAULT NULL COMMENT '최초등록일시D',
  PSSWD_ERR_FRQY int DEFAULT '0' COMMENT '비밀번호오류횟수',
  USER_IPADDR varchar(16) DEFAULT NULL COMMENT '사용자IP주소',
  PRIMARY KEY (USERID),
  KEY OCO10100_N1 (USER_IDENT_NO),
  KEY OCO10100_N2 (CUCEN_TEAM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자기본';

CREATE TABLE OCO.OCO10109 (
  USERID_REQST_SEQ bigint NOT NULL AUTO_INCREMENT COMMENT '사용자ID신청순번',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USERID varchar(10) DEFAULT NULL COMMENT '사용자ID',
  USERID_REQST_DT varchar(8) DEFAULT NULL COMMENT '사용자ID신청일자',
  USERID_REQST_STS_CD varchar(1) DEFAULT NULL COMMENT '사용자ID신청상태코드',
  RVW_USERID varchar(10) DEFAULT NULL COMMENT '검토사용자ID',
  RVW_DT varchar(8) DEFAULT NULL COMMENT '검토일자',
  AUTHZ_USERID varchar(10) DEFAULT NULL COMMENT '승인사용자ID',
  AUTHZ_DT varchar(8) DEFAULT NULL COMMENT '승인일자',
  GVBK_RESON_CNTNT varchar(1000) DEFAULT NULL COMMENT '반려사유내용',
  AUTHZ_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '승인사용자IP주소',
  REQST_RESON_CNTNT varchar(1000) DEFAULT NULL COMMENT '신청사유내용',
  PRIMARY KEY (USERID_REQST_SEQ)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자ID신청목록';

CREATE TABLE OCO.OCO10110 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USER_ROLE_NM varchar(50) DEFAULT NULL COMMENT '사용자역할명',
  USER_ROLE_DESC varchar(200) DEFAULT NULL COMMENT '사용자역할설명',
  USER_ATHRTY_GROUP_CD varchar(3) DEFAULT NULL COMMENT '사용자역할그룹코드',
  LOCK_ATHRTY_CL_CD varchar(1) DEFAULT NULL COMMENT '잠금권한구분코드',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  PRIMARY KEY (USER_ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할기본';

CREATE TABLE OCO.OCO10101 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  PRIMARY KEY (USER_ROLE_ID,USERID),
  KEY OCO10101_TEST (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할내역';

CREATE TABLE OCO.OCO10120 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  PRIMARY KEY (USER_ROLE_ID,MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할메뉴내역';

CREATE TABLE OCO.OCO10121 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '버튼ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  PRIMARY KEY (USER_ROLE_ID,SCREN_ID,BTTN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할버튼내역';

CREATE TABLE OCO.OCO10111 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL COMMENT '역할부서팀코드',
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL COMMENT '역할매핑직책코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ROLE_DEPT_TEAM_CL_CD varchar(1) DEFAULT NULL COMMENT '역할부서팀구분코드',
  ACCNT_CRAT_AUTO_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '계정생성자동여부',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할부서팀코드';

CREATE TABLE OCO.OCO10113 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL COMMENT '역할부서팀코드',
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL COMMENT '역할매핑직책코드',
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD,USER_ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할부서팀코드매핑내역';

CREATE TABLE OCO.OCO10106 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  PRIMARY KEY (USERID,MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자추가메뉴내역';

CREATE TABLE OCO.OCO10107 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '버튼ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  PRIMARY KEY (USERID,SCREN_ID,BTTN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자추가화면버튼내역';

CREATE TABLE OCO.OCO10130 (
  ATHRTY_REQST_SEQ bigint NOT NULL AUTO_INCREMENT COMMENT '권한신청순번',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_STS_CD varchar(1) DEFAULT NULL COMMENT '권한신청상태코드',
  USERID varchar(10) DEFAULT NULL COMMENT '사용자ID',
  REQST_RESON_CNTNT varchar(1000) DEFAULT NULL COMMENT '신청사유내용',
  INDIV_INFO_YN varchar(1) DEFAULT 'N' COMMENT '개인정보여부',
  RPA_USER_YN varchar(1) DEFAULT 'N' COMMENT 'RPA사용자여부',
  REQST_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '신청사용자IP주소',
  PRIMARY KEY (ATHRTY_REQST_SEQ)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자권한신청기본';

CREATE TABLE OCO.OCO10131 (
  ATHRTY_REQST_SEQ bigint NOT NULL COMMENT '권한신청순번',
  ATHRTY_REQST_OP_DTM varchar(14) NOT NULL COMMENT '권한신청처리일시',
  ATHRTY_REQST_STS_CD varchar(1) NOT NULL COMMENT '권한신청상태코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  SETTL_USERID varchar(10) DEFAULT NULL COMMENT '결제사용자ID',
  SETTL_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '결제사용자IP주소',
  GVBK_RESON_CNTNT varchar(1000) DEFAULT NULL COMMENT '반려사유내용',
  PRIMARY KEY (ATHRTY_REQST_SEQ,ATHRTY_REQST_OP_DTM,ATHRTY_REQST_STS_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자권한신청처리내역';

CREATE TABLE OCO.OCO10132 (
  ATHRTY_REQST_SEQ bigint NOT NULL COMMENT '권한신청순번',
  ATHRTY_REQST_DTL_SEQ int NOT NULL COMMENT '권한신청내역순번',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USER_ROLE_ID varchar(4) DEFAULT NULL COMMENT '사용자역할ID',
  MENU_ID varchar(12) DEFAULT NULL COMMENT '메뉴ID',
  SCREN_ID varchar(10) DEFAULT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) DEFAULT NULL COMMENT '버튼ID',
  ATHRTY_ADDN_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '권한추가여부',
  PRIMARY KEY (ATHRTY_REQST_SEQ,ATHRTY_REQST_DTL_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자권한신청내역';

CREATE TABLE OCO.OCO10210 (
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99' COMMENT '담당업무그룹코드',
  MENU_TYPE_CD varchar(1) DEFAULT NULL COMMENT '메뉴유형코드',
  SCREN_EXCUT_CL_CD varchar(1) DEFAULT NULL COMMENT '화면실행구분코드',
  MENU_NM varchar(100) DEFAULT NULL COMMENT '메뉴명',
  MENU_DESC varchar(500) DEFAULT NULL COMMENT '메뉴설명',
  MENU_STEP_VAL int NOT NULL DEFAULT '0' COMMENT '메뉴단계값',
  SORT_SEQN int DEFAULT '0' COMMENT '정렬순서',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  MENU_EXPSE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '메뉴노출여부',
  SUPER_MENU_ID varchar(12) DEFAULT NULL COMMENT '상위메뉴ID',
  SCREN_ID varchar(10) DEFAULT NULL COMMENT '화면ID',
  LINKA_SYSTM_TAG_CNTNT varchar(500) DEFAULT NULL COMMENT '연동시스템태그내용',
  PRIMARY KEY (MENU_ID),
  KEY OCO10210_N1 (SCREN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_메뉴기본';

CREATE TABLE OCO.OCO10220 (
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99' COMMENT '담당업무그룹코드',
  SCREN_NM varchar(100) DEFAULT NULL COMMENT '화면명',
  SCREN_DESC varchar(100) DEFAULT NULL COMMENT '화면설명',
  SCREN_URLADDR varchar(100) DEFAULT NULL COMMENT '화면URL주소',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  SCREN_CL_CD varchar(1) DEFAULT NULL COMMENT '화면구분코드',
  SCREN_SIZE_CL_CD varchar(1) DEFAULT NULL COMMENT '화면크기구분코드',
  SCREN_WIDTH_SIZE int DEFAULT NULL COMMENT '화면가로크기',
  SCREN_VRTLN_SIZE int DEFAULT NULL COMMENT '화면세로크기',
  SCREN_START_TOP_CODN int DEFAULT NULL COMMENT '화면시작상단좌표',
  SCREN_START_LEFT_CODN int DEFAULT NULL COMMENT '화면시작좌측좌표',
  PRIMARY KEY (SCREN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_화면기본';

CREATE TABLE OCO.OCO10230 (
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '버튼ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  BTTN_NM varchar(100) DEFAULT NULL COMMENT '버튼명',
  BTTN_DESC varchar(500) DEFAULT NULL COMMENT '버튼설명',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  API_ID int DEFAULT NULL COMMENT 'APIID',
  CRUD_CL_CD varchar(1) NOT NULL DEFAULT 'R' COMMENT 'CRUD구분코드',
  PRIMARY KEY (SCREN_ID,BTTN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_화면버튼기본';

CREATE TABLE OCO.OCO10104 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  SORT_SEQN int DEFAULT '0' COMMENT '정렬순서',
  PRIMARY KEY (USERID,MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자즐겨찾기메뉴목록';

CREATE TABLE OCO.OCO10105 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  SORT_SEQN int DEFAULT '0' COMMENT '정렬순서',
  PRIMARY KEY (USERID,MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자바로가기메뉴목록';

CREATE TABLE OCO.OCO10141 (
  USER_SCREN_CNSTTE_SEQ int NOT NULL AUTO_INCREMENT COMMENT '사용자화면구성순번',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  USER_SCREN_CNSTTE_NM varchar(100) DEFAULT NULL COMMENT '사용자화면구성명',
  USER_INTI_SCREN_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '사용자초기화면여부',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  PRIMARY KEY (USER_SCREN_CNSTTE_SEQ)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자화면구성기본';

CREATE TABLE OCO.OCO10142 (
  USER_SCREN_CNSTTE_SEQ int NOT NULL COMMENT '사용자화면구성순번',
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  SCREN_START_XCOO float DEFAULT NULL COMMENT '화면시작X좌표',
  SCREN_START_YCOO float DEFAULT NULL COMMENT '화면시작Y좌표',
  SCREN_WIDTH_SIZE int DEFAULT NULL COMMENT '화면가로크기',
  SCREN_VRTLN_SIZE int DEFAULT NULL COMMENT '화면세로크기',
  PRIMARY KEY (USER_SCREN_CNSTTE_SEQ,SCREN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자화면구성상세';

CREATE TABLE OCO.OCO10103 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  CHNG_COL_ENGSH_NM varchar(50) NOT NULL COMMENT '변경컬럼영문명',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CHNG_COL_VAL varchar(600) DEFAULT NULL COMMENT '변경컬럼값',
  PRIMARY KEY (USERID,CHNG_COL_ENGSH_NM,CHNG_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자변경이력';

CREATE TABLE OCO.OCO10190 (
  USER_ACTVY_SEQ bigint NOT NULL AUTO_INCREMENT COMMENT '사용자활동순번',
  USER_ACTVY_DTM varchar(14) NOT NULL COMMENT '사용자활동일시',
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  USER_ACTVY_TYPE_CD varchar(3) DEFAULT NULL COMMENT '사용자활동유형코드',
  CONN_IPADDR varchar(16) DEFAULT NULL COMMENT '접속IP주소',
  SCREN_ID varchar(10) DEFAULT NULL COMMENT '화면ID',
  SYSTM_CTGRY_CD varchar(3) DEFAULT NULL COMMENT '시스템분류코드',
  DWNLD_RESON_CNTNT varchar(200) DEFAULT NULL COMMENT '다운로드사유내용',
  ACCSS_TOKEN_VAL varchar(1000) DEFAULT NULL COMMENT '접근토큰값',
  REFSH_TOKEN_VAL varchar(36) DEFAULT NULL COMMENT '새로고침토큰값',
  PRIMARY KEY (USER_ACTVY_SEQ,USER_ACTVY_DTM,USERID),
  KEY OCO10190_N1 (USERID,USER_ACTVY_TYPE_CD,USER_ACTVY_DTM DESC),
  KEY OCO10190_N2 (USER_ACTVY_DTM)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자활동로그';

CREATE TABLE OCO.OCO10112 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  CRUD_CL_CD varchar(1) NOT NULL COMMENT 'CRUD구분코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  DEPTCD varchar(6) DEFAULT NULL COMMENT '부서코드',
  DEPT_NM varchar(50) DEFAULT NULL COMMENT '부서명',
  CUCEN_TEAM_CD varchar(3) DEFAULT NULL COMMENT '고객센터팀코드',
  CUCEN_TEAM_NM varchar(100) DEFAULT NULL COMMENT '고객센터팀명',
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '변경사용자IP주소',
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (USERID,USER_ROLE_ID,CHNG_DTM,CRUD_CL_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할변경이력';

CREATE TABLE OCO.OCO10122 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CRUD_CL_CD varchar(1) DEFAULT NULL COMMENT 'CRUD구분코드',
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '변경사용자IP주소',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (USER_ROLE_ID,MENU_ID,CHNG_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할메뉴이력';

CREATE TABLE OCO.OCO10123 (
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '버튼ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CRUD_CL_CD varchar(1) DEFAULT NULL COMMENT 'CRUD구분코드',
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '변경사용자IP주소',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (USER_ROLE_ID,SCREN_ID,BTTN_ID,CHNG_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할버튼이력';

CREATE TABLE OCO.OCO10116 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  MENU_ID varchar(12) NOT NULL COMMENT '메뉴ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  CRUD_CL_CD varchar(1) NOT NULL COMMENT 'CRUD구분코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ char(18) DEFAULT NULL COMMENT '권한신청순번',
  CHNG_USER_IPADDR char(18) DEFAULT NULL COMMENT '변경사용자IP주소',
  CHNG_RESON_CNTNT varchar(400) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (USERID,MENU_ID,CHNG_DTM,CRUD_CL_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자추가메뉴이력';

CREATE TABLE OCO.OCO10117 (
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  SCREN_ID varchar(10) NOT NULL COMMENT '화면ID',
  BTTN_ID varchar(30) NOT NULL COMMENT '버튼ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  CRUD_CL_CD varchar(1) NOT NULL COMMENT 'CRUD구분코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATHRTY_REQST_SEQ char(18) DEFAULT NULL COMMENT '권한신청순번',
  CHNG_USER_IPADDR char(18) DEFAULT NULL COMMENT '변경사용자IP주소',
  CHNG_RESON_CNTNT varchar(400) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (USERID,SCREN_ID,BTTN_ID,CHNG_DTM,CRUD_CL_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자추가화면버튼이력';

CREATE TABLE OCO.OCO10114 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL COMMENT '역할부서팀코드',
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL COMMENT '역할매핑직책코드',
  USER_ROLE_ID varchar(4) NOT NULL COMMENT '사용자역할ID',
  CHNG_DTM varchar(14) NOT NULL COMMENT '변경일시',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CRUD_CL_CD varchar(1) DEFAULT NULL COMMENT 'CRUD구분코드',
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL COMMENT '변경사용자IP주소',
  ATHRTY_REQST_SEQ bigint DEFAULT NULL COMMENT '권한신청순번',
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL COMMENT '변경사유내용',
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD,USER_ROLE_ID,CHNG_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사용자역할부서팀코드매핑이력';

CREATE TABLE OCO.OCO20100 (
  CMMN_CD varchar(30) NOT NULL COMMENT '공통코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  SKSH_SYSTM_CD varchar(3) NOT NULL DEFAULT 'OSS' COMMENT 'SK쉴더스시스템코드',
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99' COMMENT '담당업무그룹코드',
  BSS_CMMN_CD varchar(6) DEFAULT NULL COMMENT 'BSS공통코드',
  CMMN_CD_NM varchar(50) NOT NULL COMMENT '공통코드명',
  CMMN_CD_DESC varchar(100) DEFAULT NULL COMMENT '공통코드설명',
  CMMN_CD_VAL_LENTH int DEFAULT '0' COMMENT '공통코드값길이',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  REFRN_ATTR_NM1 varchar(200) DEFAULT NULL COMMENT '참조속성명1',
  REFRN_ATTR_NM2 varchar(200) DEFAULT NULL COMMENT '참조속성명2',
  REFRN_ATTR_NM3 varchar(200) DEFAULT NULL COMMENT '참조속성명3',
  REFRN_ATTR_NM4 varchar(200) DEFAULT NULL COMMENT '참조속성명4',
  REFRN_ATTR_NM5 varchar(200) DEFAULT NULL COMMENT '참조속성명5',
  REFRN_ATTR_NM6 varchar(200) DEFAULT NULL COMMENT '참조속성명6',
  REFRN_ATTR_NM7 varchar(200) DEFAULT NULL COMMENT '참조속성명7',
  REFRN_ATTR_NM8 varchar(200) DEFAULT NULL COMMENT '참조속성명8',
  REFRN_ATTR_NM9 varchar(200) DEFAULT NULL COMMENT '참조속성명9',
  REFRN_ATTR_NM10 varchar(200) DEFAULT NULL COMMENT '참조속성명10',
  BEFO_CMMN_TYPE_CD varchar(6) DEFAULT NULL COMMENT '이전공통유형코드',
  BEFO_CMMN_GROUP_CD varchar(20) DEFAULT NULL COMMENT '이전공통그룹코드',
  PRIMARY KEY (CMMN_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_공통코드';

CREATE TABLE OCO.OCO20101 (
  CMMN_CD varchar(30) NOT NULL COMMENT '공통코드',
  CMMN_CD_VAL varchar(40) NOT NULL COMMENT '공통코드값',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  CMMN_CD_VAL_NM varchar(100) NOT NULL COMMENT '공통코드값명',
  CMMN_CD_VAL_DESC varchar(300) DEFAULT NULL COMMENT '공통코드값설명',
  SORT_SEQN int DEFAULT 0 COMMENT '정렬순서',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  REFRN_ATTR_VAL1 varchar(100) DEFAULT NULL COMMENT '참조속성값1',
  REFRN_ATTR_VAL2 varchar(100) DEFAULT NULL COMMENT '참조속성값2',
  REFRN_ATTR_VAL3 varchar(100) DEFAULT NULL COMMENT '참조속성값3',
  REFRN_ATTR_VAL4 varchar(100) DEFAULT NULL COMMENT '참조속성값4',
  REFRN_ATTR_VAL5 varchar(100) DEFAULT NULL COMMENT '참조속성값5',
  REFRN_ATTR_VAL6 varchar(100) DEFAULT NULL COMMENT '참조속성값6',
  REFRN_ATTR_VAL7 varchar(100) DEFAULT NULL COMMENT '참조속성값7',
  REFRN_ATTR_VAL8 varchar(100) DEFAULT NULL COMMENT '참조속성값8',
  REFRN_ATTR_VAL9 varchar(100) DEFAULT NULL COMMENT '참조속성값9',
  REFRN_ATTR_VAL10 varchar(100) DEFAULT NULL COMMENT '참조속성값10',
  SUPER_CMMN_CD varchar(30) DEFAULT NULL COMMENT '상위공통코드',
  SUPER_CMMN_CD_VAL varchar(30) DEFAULT NULL COMMENT '상위공통코드값',
  PRIMARY KEY (CMMN_CD,CMMN_CD_VAL),
  KEY OCO20101_N1 (REFRN_ATTR_VAL1,CMMN_CD_VAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_공통코드상세';

CREATE TABLE OCO.OCO30900 (
  ATAC_FILE_NO bigint NOT NULL AUTO_INCREMENT COMMENT '첨부파일번호',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ATAC_FILE_TYPE_CD varchar(5) NOT NULL COMMENT '첨부파일유형코드',
  ATAC_FILE_TASK_CL_CD varchar(3) DEFAULT NULL COMMENT '첨부파일업무구분코드',
  ATAC_FILE_NM varchar(100) NOT NULL COMMENT '첨부파일명',
  ATAC_FILE_SIZE bigint DEFAULT NULL COMMENT '첨부파일크기',
  ATAC_FILE_PATH_NM varchar(200) NOT NULL COMMENT '첨부파일경로명',
  ATAC_FILE_LOC_URLADDR varchar(100) DEFAULT NULL COMMENT '첨부파일위치URL주소',
  ATAC_FILE_STS_CD varchar(1) DEFAULT NULL COMMENT '첨부파일상태코드',
  PRIMARY KEY (ATAC_FILE_NO)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='공통_첨부파일내역';

CREATE TABLE OCO.OCO10240 (
  LINKA_SYSTM_NM varchar(10) NOT NULL COMMENT '연동시스템명',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  FST_REGR_ID varchar(10) NOT NULL COMMENT '최초등록자ID',
  FST_REG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일시D',
  CONN_PSBTY_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '접속가능여부',
  PRIMARY KEY (LINKA_SYSTM_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인터페이스_연동시스템절체기준';

CREATE TABLE OCO.OCO40100 (
  APRO_GROUP_ID int NOT NULL AUTO_INCREMENT COMMENT '응용프로그램그룹ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  APRO_TYPE_CL_CD varchar(1) DEFAULT NULL COMMENT '응용프로그램유형구분코드',
  APRO_TASK_CL_CD varchar(3) DEFAULT NULL COMMENT '응용프로그램업무구분코드',
  APRO_GROUP_CL_NM varchar(30) DEFAULT NULL COMMENT '응용프로그램그룹구분명',
  APRO_GROUP_DESC varchar(1000) DEFAULT NULL COMMENT '응용프로그램그룹설명',
  PRIMARY KEY (APRO_GROUP_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='시스템관리_응용프로그램그룹기본';


CREATE TABLE OCO.OCO40110 (
  API_ID int NOT NULL AUTO_INCREMENT COMMENT 'APIID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  APRO_GROUP_ID int DEFAULT NULL COMMENT '응용프로그램그룹ID',
  API_NM varchar(100) DEFAULT NULL COMMENT 'API명',
  API_DESC varchar(200) DEFAULT NULL COMMENT 'API설명',
  API_LOC_URLADDR varchar(300) DEFAULT NULL COMMENT 'API위치URL주소',
  HTT_METHOD_VAL varchar(10) DEFAULT NULL COMMENT 'HTT메소드값',
  API_REQ_CNTNT text COMMENT 'API요청내용',
  API_RESP_CNTNT text COMMENT 'API응답내용',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  PRIMARY KEY (API_ID),
  KEY OCO40110_N1 (HTT_METHOD_VAL,API_LOC_URLADDR)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='시스템관리_API기본';

CREATE TABLE OCO.OCO40111 (
  API_EXECT_DTL_SEQ bigint NOT NULL AUTO_INCREMENT COMMENT 'API수행내역순번',
  API_EXECT_START_DTMT timestamp NOT NULL COMMENT 'API수행시작일시T',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  API_RESP_TIME int DEFAULT NULL COMMENT 'API응답시간',
  API_ID int NOT NULL COMMENT 'APIID',
  API_RESP_STS_VAL int DEFAULT NULL COMMENT 'API응답상태값',
  ERR_CNTNT text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '오류내용',
  API_EXECT_USERID varchar(10) DEFAULT NULL COMMENT 'API수행사용자ID',
  CONN_IPADDR varchar(16) DEFAULT NULL COMMENT '접속IP주소',
  PRIMARY KEY (API_EXECT_DTL_SEQ,API_EXECT_START_DTMT),
  KEY OCO40111_N2 (API_ID),
  KEY OCO40111_N1 (API_EXECT_START_DTMT,API_RESP_STS_VAL)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='시스템관리_API수행내역';

CREATE TABLE OCO.OCO40112 (
  API_EXECT_DT varchar(8) NOT NULL COMMENT 'API수행일자',
  API_ID int NOT NULL COMMENT 'APIID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  API_EXECT_CCNT bigint NOT NULL DEFAULT 0 COMMENT 'API수행건수',
  PRIMARY KEY (API_EXECT_DT,API_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='시스템관리_API수행통계';


CREATE TABLE OCO.OCO50100 (
  EMPNO varchar(8) NOT NULL COMMENT '사원번호',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  EMP_KRN_NM varchar(30) DEFAULT NULL COMMENT '사원한글명',
  EMP_ENGLNM varchar(20) NOT NULL COMMENT '사원영문성',
  EMP_ENGFNM varchar(20) DEFAULT NULL COMMENT '사원영문이름',
  DEPTCD varchar(6) NOT NULL COMMENT '부서코드',
  BTHDY varchar(8) DEFAULT NULL COMMENT '생년월일',
  OWHM_PHNO varchar(14) NOT NULL COMMENT '자택전화번호',
  MPHNO varchar(14) DEFAULT NULL COMMENT '휴대전화번호',
  GROUP_ENTCP_DT varchar(8) NOT NULL COMMENT '그룹입사일자',
  TCOM_ENTCP_DT varchar(8) NOT NULL COMMENT '당사입사일자',
  CURTP_OFORD_DT varchar(8) NOT NULL COMMENT '현직발령일자',
  CURTP_OFORD_CD varchar(3) NOT NULL COMMENT '현직발령코드',
  RESG_DT varchar(8) DEFAULT NULL COMMENT '퇴사일자',
  COM_CL_CD varchar(1) NOT NULL COMMENT '회사구분코드',
  CLOFP_CD varchar(3) NOT NULL COMMENT '직급코드',
  REOFO_CD varchar(3) NOT NULL COMMENT '직책코드',
  JGP_CD varchar(1) NOT NULL COMMENT '직군코드',
  VCTN_CD varchar(3) DEFAULT NULL COMMENT '직능코드',
  TEAMBR_CL_CD varchar(3) NOT NULL COMMENT '팀원구분코드',
  CLOFP_NM varchar(20) NOT NULL COMMENT '직급명',
  JGP_NM varchar(20) NOT NULL COMMENT '직군명',
  VCTN_NM varchar(20) NOT NULL COMMENT '직능명',
  EMAILADDR varchar(100) NOT NULL COMMENT '이메일주소',
  BEFO_EMPNO varchar(8) DEFAULT NULL COMMENT '이전사원번호',
  PRIMARY KEY (EMPNO),
  KEY OCO50100_N1 (JGP_NM),
  KEY OCO50100_N2 (VCTN_CD),
  KEY OCO50100_N3 (EMPNO,DEPTCD),
  KEY OCO50100_N4 (EMPNO,EMP_KRN_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_사원기본';

CREATE TABLE OCO.OCO50200 (
  DEPTCD varchar(6) NOT NULL COMMENT '부서코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  MGMT_DEPTCD varchar(6) DEFAULT NULL COMMENT '관리부서코드',
  DEPT_NM varchar(50) DEFAULT NULL COMMENT '부서명',
  ENGSH_DEPT_NM varchar(50) NOT NULL COMMENT '영문부서명',
  ENGSH_DEPT_ABBR_NM varchar(50) NOT NULL COMMENT '영문부서약어명',
  BSSMACD varchar(2) NOT NULL COMMENT 'BSS본부코드',
  SUPER_DEPTCD varchar(6) NOT NULL COMMENT '상위부서코드',
  DEPT_GRADE_CD varchar(1) NOT NULL COMMENT '부서등급코드',
  DEPT_CRAT_DT varchar(8) NOT NULL COMMENT '부서생성일자',
  DEPT_ABOL_DT varchar(8) DEFAULT NULL COMMENT '부서폐지일자',
  FEMP_DEPTCD varchar(6) DEFAULT NULL COMMENT '상근부서코드',
  WHTAX_BZPL_CD varchar(6) NOT NULL COMMENT '원천세사업장코드',
  SALS_DEPTCD varchar(6) NOT NULL COMMENT '매출부서코드',
  INV_DEPTCD varchar(6) NOT NULL COMMENT '청구부서코드',
  INVNT_WRHUS_CD varchar(6) NOT NULL COMMENT '재고창고코드',
  VAT_BZPL_CD varchar(6) NOT NULL COMMENT 'VAT사업장코드',
  ZIPCD varchar(6) NOT NULL COMMENT '우편번호',
  BASIC_ADDR varchar(200) NOT NULL COMMENT '기본주소',
  DETIL_ADDR varchar(200) NOT NULL COMMENT '상세주소',
  EXTSN_NO varchar(4) DEFAULT NULL COMMENT '내선번호',
  PHNO varchar(14) NOT NULL COMMENT '전화번호',
  FAX_NO varchar(14) NOT NULL COMMENT '팩스번호',
  BZNO varchar(10) NOT NULL COMMENT '사업자등록번호',
  BZMAN_ACQ_DT varchar(8) NOT NULL COMMENT '사업자취득일자',
  TXOFC_CD varchar(3) NOT NULL COMMENT '세무서코드',
  TXOFC_NM varchar(20) NOT NULL COMMENT '세무서명',
  COM_BSCND_NM varchar(30) NOT NULL COMMENT '회사업태명',
  COM_ITM_NM varchar(30) NOT NULL COMMENT '회사종목명',
  COM_CORP_NM varchar(50) NOT NULL COMMENT '회사법인명',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  CCNTR_CD varchar(10) DEFAULT NULL COMMENT '코스트센터코드',
  RPRTT_NM varchar(30) DEFAULT NULL COMMENT '대표자명',
  PRIMARY KEY (DEPTCD),
  KEY OCO50200_N1 (MGMT_DEPTCD),
  KEY OCO50200_N2 (DEPTCD,SUPER_DEPTCD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_부서코드';

CREATE TABLE OCO.OCO50300 (
  BSSMACD varchar(2) NOT NULL COMMENT 'BSS본부코드',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  BSS_HQ_NM varchar(50) NOT NULL COMMENT 'BSS본부명',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  PRIMARY KEY (BSSMACD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_BSS본부코드';

CREATE TABLE OCO.OCO10133 (
    AGENT_REG_SEQ INT AUTO_INCREMENT PRIMARY KEY,
    USERID VARCHAR(4),
    AGENT_ID VARCHAR(10),
    DEPTCD VARCHAR(6),
    AGENT_START_DT VARCHAR(8),
    AGENT_END_SCHDL_DT VARCHAR(8),
    AGENT_END_DT VARCHAR(8),
    END_YN VARCHAR(1),
    AGENT_REG_RESON_CNTNT VARCHAR(4000)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE OCO.OCO10195 (
    SUMR_DT CHAR(8) NOT NULL, COMMENT 'Menu statistics date (8 characters)'
    MENU_ID VARCHAR(255) NOT NULL, COMMENT 'Menu ID'
    CONN_QTY BIGINT, COMMENT 'Connection quantity (nullable)'
    PRIMARY KEY (SUMR_DT, MENU_ID) COMMENT 'Composite primary key on SUMR_DT and MENU_ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
