spring:
  config:
    import: classpath:quartz.yml

  profiles:
    group:
      local: common-env, local-env
      dev: common-env, dev-env
      stg: common-env, stg-env
      prd: common-env, prd-env
    active: local
  java:
    options: "-Xms512m -Xmx2g"
---

spring:
  config:
    activate:
      on-profile: common-env

  application:
    name: com-batch

  main:
    allow-bean-definition-overriding: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
      use-new-id-generator-mappings: false
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  sql:
    init:
      mode: never

  batch:
    jdbc:
      initialize-schema: never
      table-prefix: quartz.BATCH_
    job:
      enabled: false
      names: ${job.name:NONE}

  datasource:
    batch:
      username: com_dev
      password: qwer1234!
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
      hikari:
        pool-name: Hikari
        connection-timeout: 30000
        minimum-idle: 1
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        auto-commit: false
    quartz:
      username: com_dev
      password: qwer1234!
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
      hikari:
        pool-name: Hikari
        connection-timeout: 30000
        minimum-idle: 1
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        auto-commit: false

management:
  health:
    circuitbreakers:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /actuator

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: ./logs/${spring.application.name}.log
    max-history: 30
    max-size: 100MB
    total-size-cap: 100GB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level %logger : %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  level:
    root: INFO
    web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.adtcaps.nextoss: DEBUG

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml

kafka:
  topic:
    API-TRACE-LOG: ONM-T-LOG-API
    API-TRACE-LOG-ERR: ONM-T-LOG-API-ERR
  group-id:
    API-TRACE-LOG: onm-g-log-api
  concurrency:
    API-TRACE-LOG: 3
---

spring:
  config:
    activate:
      on-profile: local-env

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "changeme"
      timeout: 30000
      lettuce:
        pool:
          maxTotal: 8
          maxWaitMillis: 10000
          maxIdle: 8
          minIdle: 0

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type: BATCH
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      max-poll-records: 50
      fetch-min-size: 15360
      fetch-max-wait: 2000
server:
  port: 8181

---

spring:
  config:
    activate:
      on-profile: dev-env

server:
  port: 8181


---

spring:
  config:
    activate:
      on-profile: stg-env

server:
  port: 8181


---

spring:
  config:
    activate:
      on-profile: prd-env

server:
  port: 8181
