CREATE SCHEMA OOM;

CREATE TABLE OOM.OOM10310 (
    DSPSN_WORK_ID BIGINT NOT NULL AUTO_INCREMENT,
    DSPSN_WORK_NM VARCHAR(255),
    APRO_GROUP_ID VARCHAR(255),
    DSPSN_WORK_STS_NM VARCHAR(50),
    DSPSN_CLS_NM VARCHAR(255),
    DSPSN_SCHD_VAL VARCHAR(255),
    DSPSN_WORK_DESC TEXT,
    START_DTMD DATETIME,
    EXCUT_CYCLE_VAL BIGINT,
    RPTT_FRQY INT DEFAULT 0,
    RPTT_EXECT_YN BOOLEAN,
    LAST_CHNGR_ID VARCHAR(255),
    LAST_CHNG_DTMD TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DSPSN_WORK_ID)
);

CREATE TABLE OOM.OOM10311 (
    DSPSN_WORK_PARAM_SEQ BIGINT NOT NULL AUTO_INCREMENT,
    DSPSN_WORK_PARAM_NM VARCHAR(255),
    DSPSN_WORK_PARAM_TYPE_VAL VARCHAR(50),
    DSPSN_WORK_PARAM_VAL TEXT,
    LAST_CHNGR_ID VARCHAR(255),
    LAST_CHNG_DTMD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DSPSN_WORK_PARAM_SEQ)
);
