CREATE SCHEMA OCO;

CREATE TABLE OCO.OCO10100 (
  USERID VARCHAR(10) NOT NULL,
  LAST_CHNGR_ID VARCHAR(10) NOT NULL,
  LAST_CHNG_DTMD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_NM VARCHAR(30) DEFAULT NULL,
  CONN_PSSWD VARCHAR(256) DEFAULT NULL,
  PSSWD_EXPIR_DT VARCHAR(8) DEFAULT NULL,
  USER_CONT_PHNO VARCHAR(14) DEFAULT NULL,
  USER_EMAILADDR VARCHAR(100) DEFAULT NULL,
  DEPTCD VARCHAR(6) DEFAULT NULL,
  REOFO_CD VARCHAR(3) DEFAULT NULL,
  VCTN_CD VARCHAR(3) DEFAULT NULL,
  CUCEN_TEAM_CD VARCHAR(6) DEFAULT NULL,
  OFCPS_CD VARCHAR(4) DEFAULT NULL,
  USER_GROUP_CD VARCHAR(1) DEFAULT NULL,
  INNER_USER_CL_CD VARCHAR(1) DEFAULT NULL,
  USER_IDENT_NO VARCHAR(10) DEFAULT NULL,
  USERID_STS_CD VARCHAR(1) DEFAULT NULL,
  FST_REG_DTMD DATETIME DEFAULT NULL,
  PSSWD_ERR_FRQY INT DEFAULT 0,
  USER_IPADDR VARCHAR(16) DEFAULT NULL,
  PRIMARY KEY (USERID)
);

CREATE TABLE OCO.OCO10109 (
  USERID_REQST_SEQ bigint NOT NULL AUTO_INCREMENT,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USERID varchar(10) DEFAULT NULL,
  USERID_REQST_DT varchar(8) DEFAULT NULL,
  USERID_REQST_STS_CD varchar(1) DEFAULT NULL,
  RVW_USERID varchar(10) DEFAULT NULL,
  RVW_DT varchar(8) DEFAULT NULL,
  AUTHZ_USERID varchar(10) DEFAULT NULL,
  AUTHZ_DT varchar(8) DEFAULT NULL,
  GVBK_RESON_CNTNT varchar(1000) DEFAULT NULL,
  AUTHZ_USER_IPADDR varchar(16) DEFAULT NULL,
  REQST_RESON_CNTNT varchar(1000) DEFAULT NULL,
  PRIMARY KEY (USERID_REQST_SEQ)
);

CREATE TABLE OCO.OCO10110 (
  USER_ROLE_ID varchar(4) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ROLE_NM varchar(50) DEFAULT NULL,
  USER_ROLE_DESC varchar(200) DEFAULT NULL,
  USER_ATHRTY_GROUP_CD varchar(3) DEFAULT NULL,
  LOCK_ATHRTY_CL_CD varchar(1) DEFAULT NULL,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (USER_ROLE_ID)
);

CREATE TABLE OCO.OCO10101 (
  USER_ROLE_ID varchar(4) NOT NULL,
  USERID varchar(10) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID,USERID)
);

CREATE TABLE OCO.OCO10120 (
  USER_ROLE_ID varchar(4) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ROLE_ID,MENU_ID)
);

CREATE TABLE OCO.OCO10121 (
  USER_ROLE_ID varchar(4) NOT NULL,
  SCREN_ID varchar(10) NOT NULL,
  BTTN_ID varchar(30) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ROLE_ID,SCREN_ID,BTTN_ID)
);

CREATE TABLE OCO.OCO10111 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL,
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ROLE_DEPT_TEAM_CL_CD varchar(1) DEFAULT NULL,
  ACCNT_CRAT_AUTO_YN varchar(1) NOT NULL DEFAULT 'Y',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD)
);

CREATE TABLE OCO.OCO10113 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL,
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL,
  USER_ROLE_ID varchar(4) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD,USER_ROLE_ID)
);

CREATE TABLE OCO.OCO10106 (
  USERID varchar(10) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  PRIMARY KEY (USERID,MENU_ID)
);

CREATE TABLE OCO.OCO10107 (
  USERID varchar(10) NOT NULL,
  SCREN_ID varchar(10) NOT NULL,
  BTTN_ID varchar(30) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  PRIMARY KEY (USERID,SCREN_ID,BTTN_ID)
);

CREATE TABLE OCO.OCO10130 (
  ATHRTY_REQST_SEQ bigint,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_STS_CD varchar(1) DEFAULT NULL,
  USERID varchar(10) DEFAULT NULL,
  REQST_RESON_CNTNT varchar(1000) DEFAULT NULL,
  INDIV_INFO_YN varchar(1) DEFAULT 'N',
  RPA_USER_YN varchar(1) DEFAULT 'N',
  REQST_USER_IPADDR varchar(16) DEFAULT NULL,
  PRIMARY KEY (ATHRTY_REQST_SEQ)
);

CREATE TABLE OCO.OCO10131 (
  ATHRTY_REQST_SEQ bigint NOT NULL,
  ATHRTY_REQST_OP_DTM varchar(14) NOT NULL,
  ATHRTY_REQST_STS_CD varchar(1) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SETTL_USERID varchar(10) DEFAULT NULL,
  SETTL_USER_IPADDR varchar(16) DEFAULT NULL,
  GVBK_RESON_CNTNT varchar(1000) DEFAULT NULL,
  PRIMARY KEY (ATHRTY_REQST_SEQ,ATHRTY_REQST_OP_DTM,ATHRTY_REQST_STS_CD)
);

CREATE TABLE OCO.OCO10132 (
  ATHRTY_REQST_SEQ bigint NOT NULL,
  ATHRTY_REQST_DTL_SEQ int NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ROLE_ID varchar(4) DEFAULT NULL,
  MENU_ID varchar(12) DEFAULT NULL,
  SCREN_ID varchar(10) DEFAULT NULL,
  BTTN_ID varchar(30) DEFAULT NULL,
  ATHRTY_ADDN_YN varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ATHRTY_REQST_SEQ,ATHRTY_REQST_DTL_SEQ)
);

CREATE TABLE OCO.OCO10210 (
  MENU_ID varchar(12) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99',
  MENU_TYPE_CD varchar(1) DEFAULT NULL,
  SCREN_EXCUT_CL_CD varchar(1) DEFAULT NULL,
  MENU_NM varchar(100) DEFAULT NULL,
  MENU_DESC varchar(500) DEFAULT NULL,
  MENU_STEP_VAL int NOT NULL DEFAULT '0',
  SORT_SEQN int DEFAULT '0',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  MENU_EXPSE_YN varchar(1) NOT NULL DEFAULT 'Y',
  SUPER_MENU_ID varchar(12) DEFAULT NULL,
  SCREN_ID varchar(10) DEFAULT NULL,
  LINKA_SYSTM_TAG_CNTNT varchar(500) DEFAULT NULL,
  PRIMARY KEY (MENU_ID)
);

CREATE TABLE OCO.OCO10220 (
  SCREN_ID varchar(10) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99',
  SCREN_NM varchar(100) DEFAULT NULL,
  SCREN_DESC varchar(100) DEFAULT NULL,
  SCREN_URLADDR varchar(100) DEFAULT NULL,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  SCREN_CL_CD varchar(1) DEFAULT NULL,
  SCREN_SIZE_CL_CD varchar(1) DEFAULT NULL,
  SCREN_WIDTH_SIZE int DEFAULT NULL,
  SCREN_VRTLN_SIZE int DEFAULT NULL,
  SCREN_START_TOP_CODN int DEFAULT NULL,
  SCREN_START_LEFT_CODN int DEFAULT NULL,
  PRIMARY KEY (SCREN_ID)
);

CREATE TABLE OCO.OCO10230 (
  SCREN_ID varchar(10) NOT NULL,
  BTTN_ID varchar(30) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BTTN_NM varchar(100) DEFAULT NULL,
  BTTN_DESC varchar(500) DEFAULT NULL,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  API_ID int DEFAULT NULL,
  CRUD_CL_CD varchar(1) NOT NULL DEFAULT 'R',
  PRIMARY KEY (SCREN_ID,BTTN_ID)
);

CREATE TABLE OCO.OCO10104 (
  USERID varchar(10) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SORT_SEQN int DEFAULT '0',
  PRIMARY KEY (USERID,MENU_ID)
);

CREATE TABLE OCO.OCO10105 (
  USERID varchar(10) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SORT_SEQN int DEFAULT '0',
  PRIMARY KEY (USERID,MENU_ID)
);

CREATE TABLE OCO.OCO10141 (
  USER_SCREN_CNSTTE_SEQ int NOT NULL AUTO_INCREMENT,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USERID varchar(10) NOT NULL,
  USER_SCREN_CNSTTE_NM varchar(100) DEFAULT NULL,
  USER_INTI_SCREN_YN varchar(1) NOT NULL DEFAULT 'N',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (USER_SCREN_CNSTTE_SEQ)
);

CREATE TABLE OCO.OCO10142 (
  USER_SCREN_CNSTTE_SEQ int NOT NULL,
  SCREN_ID varchar(10) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SCREN_START_XCOO float DEFAULT NULL,
  SCREN_START_YCOO float DEFAULT NULL,
  SCREN_WIDTH_SIZE int DEFAULT NULL,
  SCREN_VRTLN_SIZE int DEFAULT NULL,
  PRIMARY KEY (USER_SCREN_CNSTTE_SEQ,SCREN_ID)
);

CREATE TABLE OCO.OCO10103 (
  USERID varchar(10) NOT NULL,
  CHNG_COL_ENGSH_NM varchar(50) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHNG_COL_VAL varchar(600) DEFAULT NULL,
  PRIMARY KEY (USERID,CHNG_COL_ENGSH_NM,CHNG_DTM)
);

CREATE TABLE OCO.OCO10190 (
  USER_ACTVY_SEQ bigint NOT NULL AUTO_INCREMENT,
  USER_ACTVY_DTM varchar(14) NOT NULL,
  USERID varchar(10) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ACTVY_TYPE_CD varchar(3) DEFAULT NULL,
  CONN_IPADDR varchar(16) DEFAULT NULL,
  SCREN_ID varchar(10) DEFAULT NULL,
  SYSTM_CTGRY_CD varchar(3) DEFAULT NULL,
  DWNLD_RESON_CNTNT varchar(200) DEFAULT NULL,
  ACCSS_TOKEN_VAL varchar(1000) DEFAULT NULL,
  REFSH_TOKEN_VAL varchar(36) DEFAULT NULL,
  PRIMARY KEY (USER_ACTVY_SEQ,USER_ACTVY_DTM,USERID)
);

CREATE TABLE OCO.OCO10112 (
  USERID varchar(10) NOT NULL,
  USER_ROLE_ID varchar(4) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  CRUD_CL_CD varchar(1) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  DEPTCD varchar(6) DEFAULT NULL,
  DEPT_NM varchar(50) DEFAULT NULL,
  CUCEN_TEAM_CD varchar(3) DEFAULT NULL,
  CUCEN_TEAM_NM varchar(100) DEFAULT NULL,
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL,
  PRIMARY KEY (USERID,USER_ROLE_ID,CHNG_DTM,CRUD_CL_CD)
);

CREATE TABLE OCO.OCO10122 (
  USER_ROLE_ID varchar(4) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CRUD_CL_CD varchar(1) DEFAULT NULL,
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID,MENU_ID,CHNG_DTM)
);

CREATE TABLE OCO.OCO10123 (
  USER_ROLE_ID varchar(4) NOT NULL,
  SCREN_ID varchar(10) NOT NULL,
  BTTN_ID varchar(30) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CRUD_CL_CD varchar(1) DEFAULT NULL,
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID,SCREN_ID,BTTN_ID,CHNG_DTM)
);

CREATE TABLE OCO.OCO10116 (
  USERID varchar(10) NOT NULL,
  MENU_ID varchar(12) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  CRUD_CL_CD varchar(1) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ char(18) DEFAULT NULL,
  CHNG_USER_IPADDR char(18) DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(400) DEFAULT NULL,
  PRIMARY KEY (USERID,MENU_ID,CHNG_DTM,CRUD_CL_CD)
);

CREATE TABLE OCO.OCO10117 (
  USERID varchar(10) NOT NULL,
  SCREN_ID varchar(10) NOT NULL,
  BTTN_ID varchar(30) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  CRUD_CL_CD varchar(1) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATHRTY_REQST_SEQ char(18) DEFAULT NULL,
  CHNG_USER_IPADDR char(18) DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(400) DEFAULT NULL,
  PRIMARY KEY (USERID,SCREN_ID,BTTN_ID,CHNG_DTM,CRUD_CL_CD)
);

CREATE TABLE OCO.OCO10114 (
  ROLE_DEPT_TEAM_CD varchar(6) NOT NULL,
  ROLE_MAPP_REOFO_CD varchar(4) NOT NULL,
  USER_ROLE_ID varchar(4) NOT NULL,
  CHNG_DTM varchar(14) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CRUD_CL_CD varchar(1) DEFAULT NULL,
  CHNG_USER_IPADDR varchar(16) DEFAULT NULL,
  ATHRTY_REQST_SEQ bigint DEFAULT NULL,
  CHNG_RESON_CNTNT varchar(4000) DEFAULT NULL,
  PRIMARY KEY (ROLE_DEPT_TEAM_CD,ROLE_MAPP_REOFO_CD,USER_ROLE_ID,CHNG_DTM)
);

CREATE TABLE OCO.OCO20100 (
  CMMN_CD varchar(30) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SKSH_SYSTM_CD varchar(3) NOT NULL DEFAULT 'OSS',
  CHRG_TASK_GROUP_CD varchar(2) NOT NULL DEFAULT '99',
  BSS_CMMN_CD varchar(6) DEFAULT NULL,
  CMMN_CD_NM varchar(50) NOT NULL,
  CMMN_CD_DESC varchar(100) DEFAULT NULL,
  CMMN_CD_VAL_LENTH int DEFAULT '0',
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  REFRN_ATTR_NM1 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM2 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM3 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM4 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM5 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM6 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM7 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM8 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM9 varchar(200) DEFAULT NULL,
  REFRN_ATTR_NM10 varchar(200) DEFAULT NULL,
  BEFO_CMMN_TYPE_CD varchar(6) DEFAULT NULL,
  BEFO_CMMN_GROUP_CD varchar(20) DEFAULT NULL,
  PRIMARY KEY (CMMN_CD)
);

CREATE TABLE OCO.OCO20101 (
  CMMN_CD varchar(30) NOT NULL,
  CMMN_CD_VAL varchar(40) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CMMN_CD_VAL_NM varchar(100) NOT NULL,
  CMMN_CD_VAL_DESC varchar(300) DEFAULT NULL,
  SORT_SEQN int DEFAULT 0,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  REFRN_ATTR_VAL1 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL2 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL3 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL4 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL5 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL6 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL7 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL8 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL9 varchar(100) DEFAULT NULL,
  REFRN_ATTR_VAL10 varchar(100) DEFAULT NULL,
  SUPER_CMMN_CD varchar(30) DEFAULT NULL,
  SUPER_CMMN_CD_VAL varchar(30) DEFAULT NULL,
  PRIMARY KEY (CMMN_CD,CMMN_CD_VAL)
);

CREATE TABLE OCO.OCO30900 (
  ATAC_FILE_NO bigint NOT NULL AUTO_INCREMENT,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATAC_FILE_TYPE_CD varchar(5) NOT NULL,
  ATAC_FILE_TASK_CL_CD varchar(3) DEFAULT NULL,
  ATAC_FILE_NM varchar(100) NOT NULL,
  ATAC_FILE_SIZE bigint DEFAULT NULL,
  ATAC_FILE_PATH_NM varchar(200) NOT NULL,
  ATAC_FILE_LOC_URLADDR varchar(100) DEFAULT NULL,
  ATAC_FILE_STS_CD varchar(1) DEFAULT NULL,
  PRIMARY KEY (ATAC_FILE_NO)
);

CREATE TABLE OCO.OCO10240 (
  LINKA_SYSTM_NM varchar(10) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FST_REGR_ID varchar(10) NOT NULL,
  FST_REG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONN_PSBTY_YN varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (LINKA_SYSTM_NM)
);

CREATE TABLE OCO.OCO40100 (
  APRO_GROUP_ID int NOT NULL AUTO_INCREMENT,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  APRO_TYPE_CL_CD varchar(1) DEFAULT NULL,
  APRO_TASK_CL_CD varchar(3) DEFAULT NULL,
  APRO_GROUP_CL_NM varchar(30) DEFAULT NULL,
  APRO_GROUP_DESC varchar(1000) DEFAULT NULL,
  PRIMARY KEY (APRO_GROUP_ID)
);


CREATE TABLE OCO.OCO40110 (
  API_ID int NOT NULL AUTO_INCREMENT,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  APRO_GROUP_ID int DEFAULT NULL,
  API_NM varchar(100) DEFAULT NULL,
  API_DESC varchar(200) DEFAULT NULL,
  API_LOC_URLADDR varchar(300) DEFAULT NULL,
  HTT_METHOD_VAL varchar(10) DEFAULT NULL,
  API_REQ_CNTNT text,
  API_RESP_CNTNT text,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (API_ID)
);

CREATE TABLE OCO.OCO40111 (
  API_EXECT_DTL_SEQ bigint NOT NULL AUTO_INCREMENT,
  API_EXECT_START_DTMT timestamp NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  API_RESP_TIME int DEFAULT NULL,
  API_ID int NOT NULL,
  API_RESP_STS_VAL int DEFAULT NULL,
  ERR_CNTNT text,
  API_EXECT_USERID varchar(10) DEFAULT NULL,
  CONN_IPADDR varchar(16) DEFAULT NULL,
  PRIMARY KEY (API_EXECT_DTL_SEQ,API_EXECT_START_DTMT)
);

CREATE TABLE OCO.OCO40112 (
  API_EXECT_DT varchar(8) NOT NULL,
  API_ID int NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  API_EXECT_CCNT bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (API_EXECT_DT,API_ID)
);


CREATE TABLE OCO.OCO50100 (
  EMPNO varchar(8) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EMP_KRN_NM varchar(30) DEFAULT NULL,
  EMP_ENGLNM varchar(20) NOT NULL,
  EMP_ENGFNM varchar(20) DEFAULT NULL,
  DEPTCD varchar(6) NOT NULL,
  BTHDY varchar(8) DEFAULT NULL,
  OWHM_PHNO varchar(14) NOT NULL,
  MPHNO varchar(14) DEFAULT NULL,
  GROUP_ENTCP_DT varchar(8) NOT NULL,
  TCOM_ENTCP_DT varchar(8) NOT NULL,
  CURTP_OFORD_DT varchar(8) NOT NULL,
  CURTP_OFORD_CD varchar(3) NOT NULL,
  RESG_DT varchar(8) DEFAULT NULL,
  COM_CL_CD varchar(1) NOT NULL,
  CLOFP_CD varchar(3) NOT NULL,
  REOFO_CD varchar(3) NOT NULL,
  JGP_CD varchar(1) NOT NULL,
  VCTN_CD varchar(3) DEFAULT NULL,
  TEAMBR_CL_CD varchar(3) NOT NULL,
  CLOFP_NM varchar(20) NOT NULL,
  JGP_NM varchar(20) NOT NULL,
  VCTN_NM varchar(20) NOT NULL,
  EMAILADDR varchar(100) NOT NULL,
  BEFO_EMPNO varchar(8) DEFAULT NULL,
  PRIMARY KEY (EMPNO)
);

CREATE TABLE OCO.OCO50200 (
  DEPTCD varchar(6) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MGMT_DEPTCD varchar(6) DEFAULT NULL,
  DEPT_NM varchar(50) DEFAULT NULL,
  ENGSH_DEPT_NM varchar(50) NOT NULL,
  ENGSH_DEPT_ABBR_NM varchar(50) NOT NULL,
  BSSMACD varchar(2) NOT NULL,
  SUPER_DEPTCD varchar(6) NOT NULL,
  DEPT_GRADE_CD varchar(1) NOT NULL,
  DEPT_CRAT_DT varchar(8) NOT NULL,
  DEPT_ABOL_DT varchar(8) DEFAULT NULL,
  FEMP_DEPTCD varchar(6) DEFAULT NULL,
  WHTAX_BZPL_CD varchar(6) NOT NULL,
  SALS_DEPTCD varchar(6) NOT NULL,
  INV_DEPTCD varchar(6) NOT NULL,
  INVNT_WRHUS_CD varchar(6) NOT NULL,
  VAT_BZPL_CD varchar(6) NOT NULL,
  ZIPCD varchar(6) NOT NULL,
  BASIC_ADDR varchar(200) NOT NULL,
  DETIL_ADDR varchar(200) NOT NULL,
  EXTSN_NO varchar(4) DEFAULT NULL,
  PHNO varchar(14) NOT NULL,
  FAX_NO varchar(14) NOT NULL,
  BZNO varchar(10) NOT NULL,
  BZMAN_ACQ_DT varchar(8) NOT NULL,
  TXOFC_CD varchar(3) NOT NULL,
  TXOFC_NM varchar(20) NOT NULL,
  COM_BSCND_NM varchar(30) NOT NULL,
  COM_ITM_NM varchar(30) NOT NULL,
  COM_CORP_NM varchar(50) NOT NULL,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  CCNTR_CD varchar(10) DEFAULT NULL,
  RPRTT_NM varchar(30) DEFAULT NULL,
  PRIMARY KEY (DEPTCD)
);

CREATE TABLE OCO.OCO50300 (
  BSSMACD varchar(2) NOT NULL,
  LAST_CHNGR_ID varchar(10) NOT NULL,
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BSS_HQ_NM varchar(50) NOT NULL,
  USE_YN varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (BSSMACD)
);

CREATE TABLE OCO.OCO10133 (
    AGENT_REG_SEQ INT AUTO_INCREMENT PRIMARY KEY,
    USERID VARCHAR(4),
    AGENT_ID VARCHAR(10),
    DEPTCD VARCHAR(6),
    AGENT_START_DT VARCHAR(8),
    AGENT_END_SCHDL_DT VARCHAR(8),
    AGENT_END_DT VARCHAR(8),
    END_YN VARCHAR(1),
    AGENT_REG_RESON_CNTNT VARCHAR(4000),
    LAST_CHNGR_ID VARCHAR(50) NOT NULL,
    LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OCO.OCO10195 (
    SUMR_DT CHAR(8) NOT NULL,
    MENU_ID VARCHAR(255) NOT NULL,
    CONN_QTY BIGINT,
    PRIMARY KEY (SUMR_DT, MENU_ID)
);
